

INSERT INTO LIGHT (ID, LEVEL, STATUS) VALUES (1, 20,'ON');
INSERT INTO NOISE (ID, LEVEL, STATUS) VALUES (1, 30,'ON');
INSERT INTO ROOM (ID, LIGHT_ID, NOISE_ID) VALUES (1, 1, 1);

INSERT INTO LIGHT (ID, LEVEL, STATUS) VALUES (2, 50,'OFF');
INSERT INTO NOISE (ID, LEVEL, STATUS) VALUES (2, 50,'OFF');
INSERT INTO ROOM (ID, LIGHT_ID, NOISE_ID) VALUES (2, 2, 2);

INSERT INTO LIGHT (ID, LEVEL, STATUS) VALUES (3, 20,'ON');
INSERT INTO NOISE (ID, LEVEL, STATUS) VALUES (3, 30,'ON');
INSERT INTO ROOM (ID, LIGHT_ID, NOISE_ID) VALUES (3, 3, 3);

INSERT INTO LIGHT (ID, LEVEL, STATUS) VALUES (4, 50,'OFF');
INSERT INTO NOISE (ID, LEVEL, STATUS) VALUES (4, 50,'OFF');
INSERT INTO ROOM (ID, LIGHT_ID, NOISE_ID) VALUES (4, 4, 4);

INSERT INTO LIGHT (ID, LEVEL, STATUS) VALUES (5, 20,'ON');
INSERT INTO NOISE (ID, LEVEL, STATUS) VALUES (5, 30,'ON');
INSERT INTO ROOM (ID, LIGHT_ID, NOISE_ID) VALUES (5, 5, 5);

INSERT INTO LIGHT (ID, LEVEL, STATUS) VALUES (6, 50,'OFF');
INSERT INTO NOISE (ID, LEVEL, STATUS) VALUES (6, 50,'OFF');
INSERT INTO ROOM (ID, LIGHT_ID, NOISE_ID) VALUES (6, 6, 6);

INSERT INTO LIGHT (ID, LEVEL, STATUS) VALUES (7, 20,'ON');
INSERT INTO NOISE (ID, LEVEL, STATUS) VALUES (7, 30,'ON');
INSERT INTO ROOM (ID, LIGHT_ID, NOISE_ID) VALUES (7, 7, 7);

